projectSettings:
  accountName: db
  partitionKey: /userId
  databaseName: UltramarineDB
local:
  connectionString: AccountEndpoint=https://localhost:8081;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
  containerName: items-local
production:
  connectionString: ''
  containerName: items-prod
  resourceGroup: db-rg
