projectSettings:
  queueName: tasks
  maxDeliveryAttempts: 5
local:
  connectionString: UseDevelopmentStorage=true
  containerName: tasks
  resourceGroup: ''
production:
  connectionString: ''
  containerName: tasks
  resourceGroup: ultramarine-resources
